### PR TITLE
Fix parameter order for meteocalc.feels_like()

### PR DESCRIPTION
**Pull request by frasergr**
I noticed the "feels like" value in HA was wrong and after a bit of digging found the parameter order was incorrect for the meteocalc.feels_like() function. See here: https://github.com/malexer/meteocalc/blob/0104aed770b8ddc39d2c62173a42b5065cad339d/meteocalc/feelslike_temperature.py#L8

### CODE REVIEW

**Comment by pvizeli** [comment]
lgtm, please fix the CI and then we can merge it

**Comment by Wildcat1** [comment]
Did this ever get fixed since I still see windchill showing unavailable ?

**Comment by frasergr** [comment]
This PR fixed "feels like" not "windchill"

**Comment by Wildcat1** [comment]
Thanks for clarifying. So are others still seeing an issue with windchill? I know mine goes from Unknown to populated to unknown to unavailable etc

**Comment by berezhinskiy** [comment]
Same problem - it becomes unavailable occasionally.

**Pull request merged**
