### PR TITLE
Ignore SOILADx calibration sensor values

### PR DESCRIPTION
**Pull request by sam-ward**
Add additional sensor value mappings to ignore the soiladx soil moisture sensor calibration values being sent since the v1.7.7 firmware update.

### CODE REVIEW

**Comment by sam-ward** [comment]
This should resolve https://github.com/home-assistant/core/issues/102738

**Review by Bre77 — APPROVED** [review]

**Review by pvizeli — COMMENTED** [review]
Why ignore?

**Comment by sam-ward** [comment]
Probably a bad assumption on my part, but I didn't see the point of always capturing what is essentially a static value.   I guess it could be exposed as a diagnostic value if there's merit in it (assuming we can work out the scaling between the raw value and what the app shows).

**Comment by pvizeli** [comment]
Close in flavor of https://github.com/home-assistant-libs/aioecowitt/pull/145

**Pull request closed without merging**
